# Makefile for the anchors documentation pipeline.
#
# The documentation is generated LOCALLY and its outputs are COMMITTED — CI does
# not build the docs (capturing the screenshots needs a licensed Nuke plus every
# gizmo the example comps reference, which is too heavy for CI). Run these
# targets on a workstation that has Nuke and the toolchain, then commit the
# regenerated docs/img/*.png and docs/anchors-user-guide.pdf.
#
# Screenshots are produced by nuke-screenshotter
# (https://github.com/charlesangus/nuke-screenshotter), which drives a real Nuke
# session under a virtual framebuffer.
#
# Common targets:
#   make                 Regenerate every screenshot and build the user-guide PDF.
#   make screenshots     Regenerate every PNG in docs/img/ (examples, DAG, GUI).
#   make pdf             Build docs/anchors-user-guide.pdf (committed).
#   make clean           Remove Nuke autosave/backup spill (never committed docs).
#
# The DAG screenshots come from HAND-CRAFTED .nk sources — the example comps in
# $(EXAMPLES) and the reconnect fixture in $(FIXTURE). They are committed source,
# edited by hand, and never regenerated by this Makefile; it only reads them.
#
# Overridable variables:
#   SCREENSHOTTER_DIR   Where nuke-screenshotter is cloned.
#   PANDOC / PDF_ENGINE Markdown-to-PDF toolchain.
#   NUKE_EXEC (env)     Path to the nuke executable, if not on PATH (read by the
#                       screenshotter; otherwise it is discovered via PATH).
#
# Prerequisites: a licensed interactive Nuke, plus xvfb-run, pandoc and a LaTeX
# engine (xelatex) on the host. On headless Linux install xvfb (`apt install
# xvfb`); the screenshotter wraps Nuke in xvfb-run automatically.

# Use '>' as the recipe prefix so recipe lines do not depend on literal tabs.
.RECIPEPREFIX = >

SCREENSHOTTER_REPO ?= https://github.com/charlesangus/nuke-screenshotter.git
SCREENSHOTTER_DIR ?= $(HOME)/nuke-screenshotter
PANDOC ?= pandoc
PDF_ENGINE ?= xelatex

DOCS_DIR := docs
IMG_DIR := $(DOCS_DIR)/img
SHOTS_DIR := $(DOCS_DIR)/screenshots
LATEX_DIR := $(DOCS_DIR)/latex
FIXTURE := $(SHOTS_DIR)/fixtures/anchors_dag.nk
# The narrative comes from two hand-crafted example comps whose screenshot:
# backdrops are captured into docs/img/. Like $(FIXTURE) they are committed
# source, edited by hand, never regenerated here.
EXAMPLES := $(DOCS_DIR)/examples-problems-solution.nk $(DOCS_DIR)/examples-workflows.nk
SCENARIOS := $(SHOTS_DIR)/scenarios/gui.json
HELPER_NUKE_PATH := $(SHOTS_DIR)/nuke_path
# The single committed user-guide PDF (the release bundles this file).
PDF := $(DOCS_DIR)/anchors-user-guide.pdf

# The PDFs are built with the studio training-document LaTeX class in docs/latex/.
# TEXINPUTS must include that directory so the engine finds training_doc.cls and
# the logo; the trailing ':' keeps the standard TeX search path. The pandoc
# template renders images inline (non-floating).
PDF_ASSETS := $(LATEX_DIR)/template.tex $(LATEX_DIR)/training_doc.cls $(LATEX_DIR)/logo.pdf
PANDOC_PDF_FLAGS := --pdf-engine=$(PDF_ENGINE) --template=$(LATEX_DIR)/template.tex \
  --resource-path=$(DOCS_DIR):$(LATEX_DIR) --toc -V classoption=11pt
PDF_TEXINPUTS := .:$(CURDIR)/$(LATEX_DIR):

# The screenshotter has zero runtime dependencies, so it runs straight from its
# checkout via PYTHONPATH — no install step required.
CAPTURE := PYTHONPATH="$(SCREENSHOTTER_DIR)" python3 -m nuke_docs_screenshotter.cli

.PHONY: all docs screenshots example-shots dag-shots gui-shots pdf screenshotter clean

all: docs

docs: screenshots pdf

# Clone the screenshotter on first use and confirm it imports.
screenshotter:
> @if [ ! -d "$(SCREENSHOTTER_DIR)" ]; then \
>   echo "Cloning nuke-screenshotter into $(SCREENSHOTTER_DIR)"; \
>   git clone --depth 1 "$(SCREENSHOTTER_REPO)" "$(SCREENSHOTTER_DIR)"; \
> fi
> @PYTHONPATH="$(SCREENSHOTTER_DIR)" python3 -c "import nuke_docs_screenshotter" \
>   && echo "nuke-screenshotter ready at $(SCREENSHOTTER_DIR)"

# Capture the narrative screenshots from the hand-crafted example comps. Each
# BackdropNode whose label starts with "screenshot:" becomes one PNG in
# $(IMG_DIR). These .nk files are committed source; this target only reads them.
example-shots: screenshotter
> @for nk in $(EXAMPLES); do \
>   test -f "$$nk" || { echo "Error: $$nk not found (hand-crafted source .nk)."; exit 1; }; \
>   NUKE_PATH="$(CURDIR)" $(CAPTURE) "$$nk" $(IMG_DIR) || exit 1; \
> done

# Capture the reconnect DAG screenshots from the hand-crafted fixture .nk.
dag-shots: screenshotter
> @test -f "$(FIXTURE)" || { echo "Error: $(FIXTURE) not found (it is the hand-crafted source .nk)."; exit 1; }
> NUKE_PATH="$(CURDIR)" $(CAPTURE) $(FIXTURE) $(IMG_DIR)

# Capture the GUI screenshots (overlay, pickers, dialogs) via scenario playback.
# The anchors plugin and the doc-only helper are placed on NUKE_PATH so the
# plugin's shortcuts are live, the pickers load the example comp, and the modal
# dialogs can be shown non-modally.
gui-shots: screenshotter
> NUKE_PATH="$(CURDIR):$(HELPER_NUKE_PATH)" $(CAPTURE) --scenarios $(SCENARIOS) --output-dir $(IMG_DIR)

screenshots: example-shots dag-shots gui-shots

pdf: $(PDF)

$(PDF): $(DOCS_DIR)/user-guide.md $(PDF_ASSETS)
> TEXINPUTS="$(PDF_TEXINPUTS)" $(PANDOC) $< -o $@ $(PANDOC_PDF_FLAGS)

clean:
> rm -f $(SHOTS_DIR)/fixtures/*.nk~ $(SHOTS_DIR)/fixtures/*.autosave $(DOCS_DIR)/*.nk~ $(DOCS_DIR)/*.autosave 2>/dev/null || true
